<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>DerailValleyDataSource</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="OpenSimGaugeAbstractions">
            <HintPath>$(SolutionDir)lib\OpenSimGaugeAbstractions.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
</Project>